### PR TITLE
completed the whole project

### PR DESCRIPTION
**Pull request by abruzy**

### CODE REVIEW

**Comment by uche-inyama** [comment]
Hi! you both, did a great Job. :fire: :rocket:
However, there are some modifications to make and we shall all be fine.

Use the html validator to ensure that, your html code meets the standard requirements, here's the link https://validator.w3.org/nu. Ensure there are no errors.

Seperating the major-sections of  your html code is a good practice. In your project, seperate the **comments section** from the **video section**. However, in summary, the sections in the project includes: **video section**, **comment section**, **sidebar section** and **navigation section**. Identify these sections in your html code and implement it.

There are no stickler checks in your pull request, kindly use this link https://github.com/microverseinc/linters-config, to ensure things are done correctly. Also, use this link for setting-up stickler:  https://stickler-ci.com/

Make your README.md more descriptive, add contents to README.md.

**Comment by stratospherique** [comment]
### Pull Request under the review by Ahmed Mahfoudh (TSE)

**Review by stratospherique — CHANGES_REQUESTED** [review]
Great Work guys :clap: . However, some changes needs to be made in order to get my approval to merge.
* [ ] In the recommendation sidebar, the need to add number of views next to your thumbnails.

* [ ] You need to set up linters for you files. Use this [guide](https://github.com/microverseinc/linters-config/tree/master/css)

* [ ] Run you `index.html` through [W3C validator](https://validator.w3.org) 

* [ ] Make your README.md more descriptive, add contents to README.md (e.g.describe your project, links to both of your repos and live preview).

# And that's it guys. When finish, kindly re-submit another code review request. :sunglasses:

**Comment by samgaco** [comment]
Hi @sabayounis and @abruzy :hand: 

#### Great work :clap: Almost there! some things before we can give you the approval:

* You have to address the failing checks by the linters.
* You have to add the number of views to the thumbnails section.
* [OPTIONAL] You could improve the readme file, maybe adding a live demo of the site.

#### Please :pray: work on these points and submit back for another code review. Regards! :muscle:

**Review by uche-inyama — APPROVED** [review]
Nice Job :muscle: 
Go ahead and merge to master branch. :smiley:

Also you can add the link to your project, go to [ GitHack ](https://raw.githack.com/) generate the link and post it on your README. :sparkles:

**Pull request merged**
